// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("red7")>]
[<assembly: AssemblyProductAttribute("red7")>]
[<assembly: AssemblyDescriptionAttribute("red7 card game using machine learning")>]
[<assembly: AssemblyVersionAttribute("1.0.1")>]
[<assembly: AssemblyFileVersionAttribute("1.0.1")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "red7"
    let [<Literal>] AssemblyProduct = "red7"
    let [<Literal>] AssemblyDescription = "red7 card game using machine learning"
    let [<Literal>] AssemblyVersion = "1.0.1"
    let [<Literal>] AssemblyFileVersion = "1.0.1"
    let [<Literal>] AssemblyConfiguration = "Release"
